name: cobble
version: 3.2
author: MrZenek
main: net.mrzenek.cobble.Main
commands:
      cobble:
               description: You can turn off/on cobblestone drop!!
               usage: Wrote /cobble help to get more information