name: cobble
version: 3.3
author: MrZenek
main: net.mrzenek.cobble.Main
commands:
      cobble:
               description: You can turn off/on cobblestone drop!!
               usage: Type /cobble help to get more information